### PR TITLE
Remove extra end comment delimiter

### PR DESCRIPTION
**Pull request by per1234**

### CODE REVIEW

**Comment by per1234** [comment]
From https://github.com/Sixaxis9/DottyTheClock/blob/master/Two_numbers_commented.ino#L3-L4: 

> And please also report any suggestion or bug you find.

Well I did, you just need to merge the pull request please.

**Comment by Sixaxis9** [comment]
Hi!
Sorry, I saw your pool request few months ago, but I was so busy with the
campaign that I completely forgot to merge it. In the next few hours (or in
a couple of days maximum) I'll review the modifies suggested and merge them.

Thank you very much for your support!

Marco.

**Comment by Sixaxis9** [comment]
Modifies done, thanks for suggesting!

**Comment by per1234** [comment]
You could have just clicked the **Merge** button.

**Comment by Sixaxis9** [comment]
Ok,
I'll do so the next time. As you could have seen I'm quite new in GitHub.
Thanks!
Marco.

**Pull request closed without merging**
